name: muhtawaana_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  get: ^4.6.5
  get_it: ^7.6.4
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.1
  dio: ^5.3.2
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  internet_connection_checker_plus: ^2.0.0
  dartz: ^0.10.1
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2
  persistent_bottom_nav_bar: ^5.0.2
  shimmer: ^3.0.0
  share_plus: ^7.1.0
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  firebase_core: ^2.16.0
  google_sign_in: ^6.1.5
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.1
  flutter_stripe: ^9.4.0
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/on_boarding/
    - assets/images/auth/
    - assets/images/icon/
    - assets/images/empty/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
    - family: Trajan Pro
      fonts:
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600